name: CI

on:
  push:
    branches: [ main, "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
  working-directory: packages/billytrend.com
  run: pnpm tsc -b --pretty false

      - name: Build SPA
  working-directory: packages/billytrend.com
  run: pnpm build

      - name: Lint
  working-directory: packages/billytrend.com
  run: pnpm lint
