name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  preview:
    runs-on: ubuntu-latest
    concurrency:
      group: pr-preview-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      contents: read
      pull-requests: write
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      PREVIEW_NAME: billytrend-spa-pr-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build SPA
        working-directory: packages/billytrend.com
        run: pnpm build

      - name: Deploy preview to workers.dev
        working-directory: packages/cf-worker
        id: deploy
        run: |
          set -euo pipefail
          # Run deploy, mirror output to logs, and capture it for parsing
          OUT=$(pnpm exec wrangler deploy --env preview --name "$PREVIEW_NAME" | tee /dev/stderr || true)
          # Extract a workers.dev URL if present in output
          URL=$(printf '%s\n' "$OUT" | sed -nE 's#.*(https://[A-Za-z0-9-]+\.[A-Za-z0-9-]+\.workers\.dev).*#\1#p' | tail -n1)
          if [ -n "${URL:-}" ]; then
            echo "url=$URL" >> "$GITHUB_OUTPUT"
          fi

      - name: Fetch workers.dev subdomain
        id: subdomain
        run: |
          set -euo pipefail
          API="https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/workers/subdomain"
          RESP=$(curl -fsSL -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" "$API" || true)
          SUB=$(printf '%s' "$RESP" | sed -nE 's/.*"subdomain":"([^"]+)".*/\1/p')
          if [ -n "${SUB:-}" ]; then
            echo "subdomain=$SUB" >> "$GITHUB_OUTPUT"
          fi

      - name: Construct preview URL
        id: url
        run: |
          set -euo pipefail
          # Prefer fetched subdomain, then repo variable, then deploy output
          SUBDOMAIN='${{ steps.subdomain.outputs.subdomain }}'
          if [ -z "$SUBDOMAIN" ]; then
            SUBDOMAIN='${{ vars.CF_WORKERS_SUBDOMAIN }}'
          fi
          DEPLOY_URL='${{ steps.deploy.outputs.url }}'
          if [ -n "$SUBDOMAIN" ]; then
            echo "url=https://${PREVIEW_NAME}.${SUBDOMAIN}.workers.dev" >> "$GITHUB_OUTPUT"
          elif [ -n "$DEPLOY_URL" ]; then
            echo "url=$DEPLOY_URL" >> "$GITHUB_OUTPUT"
          else
            echo "Could not determine preview URL. Either set CF_WORKERS_SUBDOMAIN repo variable or ensure wrangler outputs a workers.dev URL." >&2
            exit 1
          fi

      - name: Comment preview link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-link
          message: |
            Preview deployed: ${{ steps.url.outputs.url }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      PREVIEW_NAME: billytrend-spa-pr-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Delete preview worker
        working-directory: packages/cf-worker
        run: pnpm exec wrangler delete --name "$PREVIEW_NAME" --force
